resources:
  - kind: mongo-atlas-cluster
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .cluster_id
          title: '(.cluster_name + "@" + .project_name + " (" + .cluster_id + ")")'
          blueprint: '"mongo_atlas_cluster"'
          properties:
            organization_name: .organization_name
            organization_id: .organization_id
            project_name: .project_name
            project_id: .project_id
            cluster_name: .cluster_name
            cluster_id: .cluster_id
            cluster_type: .cluster_type
            cluster_alerts: .cluster_alerts
            cluster_availability: .cluster_availability
